AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Create a Cognito user poll for the wolf project
Resources:
  UserPool:
    Type: 'AWS::Cognito::UserPool'
    Properties:
      UserPoolName: TheWolf
      AliasAttributes:
        - email
      AutoVerifiedAttributes:
        - email
  UserPoolClient:
    Type: 'AWS::Cognito::UserPoolClient'
    Properties:
      ClientName: TheWolfWeb
      UserPoolId: !Ref UserPool
      GenerateSecret: false
Outputs:
  userPool:
    Description: TheWolf user pool ID
    Value: !Ref UserPool